---
# tasks file for mylb
- name: "Installing LoadBalancer"
  package:
    name: "haproxy"
    state: present
- name: "Configuring HaProxy File"
  template:
    src: "haproxy.cfg"
    dest: "/etc/haproxy/haproxy.cfg"
- name: "Replace Bind Port"
  replace:
    path: "/etc/haproxy/haproxy.cfg"
    regexp: "5000"
    replace: "8000"
- name: "Starting Haproxy Services"
  service:
    name: "haproxy"
    state: started

