---
# tasks file for myapache
- name: Installing Apache webserver
  package:
    name: "{{ p }}"
    state: present
- name: Copy webserver file
  template:
    src: "index.php"
    dest: "/var/www/html/index.php"
- name: Installing php
  package:
    name: "{{ php }}"
    state: present
- name: Stopping firewall services
  firewalld:
    port: "80/tcp"
    state: enabled
    permanent: yes
    immediate: yes
 
- name: Restarting Apache WebServer
  service:
    name: "{{ s }}"
    state: restarted

